apiVersion: apps/v1
kind: Deployment
metadata:
  name: halyard-backend
  labels:
    app: halyard
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard
      component: backend
  template:
    metadata:
      labels:
        app: halyard
        component: backend
    spec:
      containers:
        - name: halyard-backend
          image: robblovell/halyard-backend:1.5
          imagePullPolicy: Always
          env:
            - name: HALYARD_ECHO
              value: http://halyard-echo:8080
            - name: HALYARD_DATABASE
              value: mongodb://halyard-database:27017/halyard-database
          envFrom:
            - configMapRef:
                name: halyard-backend-config
          ports:
            - containerPort: 3000