apiVersion: v1
kind: ConfigMap
metadata:
  name: halyard-sails
data:
    sails-nginx-config: |
      upstream halyard-backend{
        # requests from the public facing app to the API server are routed here.
        server halyard-backend:3000;
      }

      upstream halyard-sockets{
          # requests from the public facing app to the SOCKETS server are routed here.
        server halyard-sockets:8999;
      }

      server {
          listen       80;
          server_name  localhost;

          #charset koi8-r;
          #access_log  /var/log/nginx/host.access.log  main;

          location ^~ /api {
              # requests from the public faccing app to the API server are routed here.
              proxy_pass http://halyard-backend;
          }

          location ^~ /ping {
              proxy_pass http://halyard-backend;
          }

          location ^~ /sails {
              proxy_pass http://halyard-backend;
          }

          location ^~ /sockets {
              # matches any query beginning with /api/ and halts searching
              # proxy api requests to the upstream server declared above
              proxy_pass http://halyard-sockets;

              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

              # WebSocket support
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
          }

          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
      }
---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: halyard-sails
  labels:
    app: halyard
    component: sails

spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard
      component: sails

  template:
    metadata:
      labels:
        app: halyard
        component: sails
    spec:
      containers:
        - name: halyard-sails
          image: robblovell/halyard-sails:1.5
          imagePullPolicy: Always
          env:
            - name: HALYARD_API_HOST
              value: halyard-backend
            - name: HALYARD_API_PORT
              value: '3000'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: halyard-sails-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: sails-nginx-config
      volumes:
      - name: halyard-sails-volume
        configMap:
          name: halyard-sails
