apiVersion: v1
kind: Service
metadata:
  name: sample-project-web
  labels:
    app: sample-project
    component: web
spec:
  type: LoadBalancer
  ports:
    - name: unsecure
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: sample-project
    component: web
