name: build
on: pull_request
jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip]')"
    runs-on: ubuntu-20.04
    steps:
      # Checkout the codebase
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      # Set the node version
      - name: Build on nodejs 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      # Dependencies
      - name: Install Dependencies
        run: yarn install --unsafe-perm
      # Compile the code
      - name: Compile and Test the Code
        run: |
          gulp build

